# Generated by Django 3.0 on 2019-12-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191218_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
