# Generated by Django 3.0 on 2019-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_cart_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mobno',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
