# Generated by Django 3.0.1 on 2019-12-24 12:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20191224_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productform',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[400, 400], upload_to='product_images/'),
        ),
    ]
