# Generated by Django 3.0.1 on 2019-12-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20191225_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
