# Generated by Django 3.2.2 on 2021-05-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20191225_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='productform',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
